Homework_2.task_1.KasperovichElena
elenakasperovich/ElenaKasperovich_LevelUp pull request #1
Opened 2021-08-30 09:12 UTC by elenakasperovich

Добрый день!
Отправляю на проверку домашнее задание №2, попытка №1.
спасибо

2021-09-06 19:53 UTC, khda91 requested changes
Удали пилиз лишний кусок и добавь чекстайл

2021-09-06 19:53 UTC, khda91 commented on pom.xml
> +    </properties>
Этот кусок нужно удалить, он не нужен в `pom.xml`

2021-09-07 11:38 UTC, elenakasperovich commented on pom.xml
> +    </properties>
Исправила

2021-09-18 09:42 UTC, khda91 approved these changes

2021-09-18 09:42 UTC, merged