Homework 3 kasperovich elena
elenakasperovich/ElenaKasperovich_LevelUp pull request #2
Opened 2021-09-06 07:05 UTC by elenakasperovich

Добрый день!
Представляю на проверку 3 домашнее задание.
с уважением, Елена Касперович

2021-09-06 19:59 UTC, khda91 requested changes

2021-09-06 19:59 UTC, khda91 commented on src/main/java/Homework_3/task_1/CreateDinner.java
> +                saladIngredient.name + " калорийностью на 100г - " + saladIngredient.calories + " ккал");
Для доступа к полям нужно использовать getters

2021-09-08 07:29 UTC, elenakasperovich commented on src/main/java/Homework_3/task_1/CreateDinner.java
> +                saladIngredient.name + " калорийностью на 100г - " + saladIngredient.calories + " ккал");
исправила

2021-09-18 09:56 UTC, khda91 approved these changes
Работа принята

2021-09-18 09:56 UTC, khda91 commented
Пожалуйста разреши конфликты и смёржи в мастер

2021-09-20 07:05 UTC, merged